update init-script

diff --git a/script/diaspora_init b/script/diaspora_init
--- a/script/diaspora_init
+++ b/script/diaspora_init
@@ -38,9 +38,26 @@ cd $DIASPORA_DIR
 
 . /lib/lsb/init-functions
 
+function warning() {
+  echo "WARNING: $1" >&2
+}
+
+function fatal() {
+  echo "FATAL: $1" >&2
+  exit 1
+}
+
+function on_failure() {
+  if [ $? != 0 ]
+  then
+    fatal "$1"
+  fi
+}
+
 # Setup environment
 if [ -z "$RAILS_ENV" ]; then
-  RAILS_ENV=$(bundle exec ruby ./script/get_config.rb server.rails_environment)
+  RAILS_ENV=$(bin/bundle exec ruby ./script/get_config.rb server.rails_environment)
+  on_failure "Couldn't parse config/diaspora.yml!"
   export RAILS_ENV
 fi
 
@@ -48,7 +65,8 @@ os=`uname -s`
 eval $(bundle exec ruby ./script/get_config.rb \
   port=server.port \
   single_process_mode=environment.single_process_mode? \
-  embed_sidekiq_worker=server.embed_sidekiq_worker
+  embed_sidekiq_worker=server.embed_sidekiq_worker \
+  workers=server.sidekiq_workers
 )
 
 if [ -z "$DB" ]; then
@@ -57,7 +75,7 @@ if [ -z "$DB" ]; then
 fi
 
 # Check if already running/port blocked
-function chk_service {
+function chk_service() {
   port=${1:?Missing port}
   case $os in
   *[Bb][Ss][Dd]*|Darwin)
@@ -71,82 +89,129 @@ function chk_service {
   esac
 }
 
-function get_sidekiq_pid {
+function get_sidekiq_pid() {
   ps -o %p,%a -U $USERNAME | grep sidekiq | grep -v grep | cut -f1 -d,
 }
 
-function start_checks {
+function start_checks() {
+
   # Is someone listening on the ports already? (ipv4 only test ?)
   services=$( chk_service $port )
   if [ -n "$services" ]; then
-    echo "FATAL: Error: port $port is already in use. Exiting" >&2
-    echo "     $services"
-    exit 64
+    fatal "Port $port is already in use.\n\t$services"
   fi
 
   # Check if database.yml exists
-  if [ ! -e 'config/database.yml' ]; then
-    echo 'FATAL: config/database.yml is missing! Copy over config/database.yml.example to config/database.yml and edit it properly!' >&2
-    exit 68
+  if [ ! -e "config/database.yml" ]
+  then
+    fatal "config/database.yml is missing! Copy over config/database.yml.example to config/database.yml and edit it properly!"
+  fi
+
+  # Check if diaspora.yml exists
+  if [ ! -e "config/diaspora.yml" ]
+  then
+    fatal "config/diaspora.yml is missing! Copy over config/diaspora.yml.example to config/diaspora.yml and edit it properly!"
   fi
     
   # Check if assets are precompiled
-  if [ "$RAILS_ENV" = "production" -a -z "$(find public/assets -maxdepth 1 -name 'home-*.css' -print -quit)" ]; then
-    echo "FATAL: You're running in production mode without having assets precompiled." >&2
-    echo "Now and after each update before you restart the application, run:" >&2
-    echo "bin/rake assets:precompile" >&2
-    exit 71
+  if [ "$RAILS_ENV" = "production" -a -z "$(find public/assets -maxdepth 1 -name 'home-*.css' -print -quit)" ]
+  then
+    fatal "You're running in production mode without having assets
+precompiled. Now and after each update before you restart the
+application, run:
+    bin/rake assets:precompile"
+  fi
+
+  # Check for old curl versions (see https://github.com/diaspora/diaspora/issues/4202)
+  if [ `curl -V | grep AsynchDNS | wc -l` -ne 1 ]
+  then
+    warning "
+*****************************************************************
+curl does not support async DNS, this can cause Sidekiq to crash!
+Please update curl to version 7.32, see issue
+https://github.com/diaspora/diaspora/issues/4202 for details
+*****************************************************************
+"
+  fi
+
+  command -v git > /dev/null 2>&1
+  if [ $? -eq 0 ]; then
+    # Check if git merge is in progress
+    if [ -f .git/MERGE_MODE ]; then
+      fatal "A git merge is in progress!"
+    fi
+
+    # Check if detached head state
+    git_branch_name="$(git symbolic-ref HEAD 2>/dev/null)"
+    if [ -z "$git_branch_name" ];
+    then
+      warning "You are in detached HEAD state!"
+    fi
+  fi
+
+  # Do RVM checks if RVM is being used
+  command -v rvm > /dev/null 2>&1
+  if [ $? -eq 0 ]; then
+    rvm_gemset="$(rvm current | cut -d"@" -f2)"
+    project_gemset="$(cat .ruby-gemset | tr -d " \t\n\r")"
+    if [ "$rvm_gemset" != "$project_gemset" ]; then
+      warning "Project gemset is $project_gemset but you are using $rvm_gemset"
+    fi
+  fi
+
+  # Check if bundle is complete
+  if ! bundle check > /dev/null
+  then
+    fatal "Your bundle is not up to date, run the command \"bundle install\""
   fi
 }
 
-function start_sidekiq {
+function start_sidekiq() {
   if [ "$single_process_mode" != "true" ] && [ "$embed_sidekiq_worker" != "true" ]; then
-    echo -n "Sidekiq ... "
+    echo "Starting Sidekiq ..."
     echo "--- Starting: $(date)" >>log/sidekiq.bundle.log &
-    bundle exec sidekiq &>> log/sidekiq.log &
+    cgexec -g memory:limited bundle exec sidekiq &>> log/sidekiq.log &
   fi
 }
 
-function stop_sidekiq {
+function stop_sidekiq() {
   if [ `get_sidekiq_pid | wc -l` > 0 ] ; then
-    echo -n "Sidekiq ... "
+    echo -n "Stopping Sidekiq ."
     get_sidekiq_pid | while read line; do
       kill $line
     done
+    while [ `get_sidekiq_pid | wc -l` > 0 ]; do echo -n "."; sleep 1; done
+    echo
   fi
 }
 
-function start_services {
-  echo -n "Starting: "
-
+function start_services() {
+  echo "Start Services: "
   start_sidekiq
 
-  echo "Unicorn ... "
+  echo "Starting Unicorn ... "
   bundle exec unicorn_rails -c config/unicorn.rb -D
 }
 
-function stop_services {
-  echo -n "Stopping Services: "
-  echo -n "Unicorn ... "
+function stop_services() {
+  echo "Stop Services: "
+  echo -n "Stopping Unicorn ..."
   kill -QUIT `cat $PID`
 
   stop_sidekiq
 }
 
-function restart_services {
-  echo -n "Restart Services: "
+function restart_services() {
+  echo "Restart Services: "
 
-  echo -n "Stop "
   stop_sidekiq
-  sleep 2
-  echo -n "Start "
   start_sidekiq
 
-  echo -n "Unicorn ... "
+  echo "Restart Unicorn ..."
   kill -USR2 `cat $PID`
 }
 
-function service_status {
+function service_status() {
   if status_of_proc -p $PID unicorn_rails > /dev/null; then
     echo "Unicorn is running"
   else
@@ -176,7 +241,6 @@ case "$1" in
   ;;
   stop)
     stop_services
-    sleep 2
     echo
     service_status
   ;;
